# Generated by Django 2.0.5 on 2018-09-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=12)),
                ('p_name', models.CharField(max_length=42)),
                ('email_id', models.EmailField(max_length=75)),
                ('contact', models.IntegerField(max_length=10)),
                ('sport_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
