# Generated by Django 2.0.5 on 2018-09-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmanagementsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
