# Generated by Django 2.0.5 on 2018-09-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmanagementsystem', '0002_auto_20180921_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
