# Generated by Django 2.0.5 on 2018-09-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmanagementsystem', '0009_auto_20180921_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_id', models.CharField(max_length=12)),
                ('c_name', models.CharField(max_length=42)),
                ('coach_type', models.CharField(max_length=10)),
                ('experience', models.IntegerField()),
                ('contact', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('s_name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sportsmanagementsystem.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=12)),
                ('about', models.TextField(max_length=42)),
                ('DateTimeField', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification_id', models.IntegerField()),
                ('sender', models.CharField(max_length=10)),
                ('receiver', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('send_date', models.DateTimeField()),
                ('sport_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sportsmanagementsystem.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('performance', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('sport_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sportsmanagementsystem.Sport')),
                ('student_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sportsmanagementsystem.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tournament_name', models.CharField(max_length=12)),
                ('team_1', models.CharField(max_length=10)),
                ('team_2', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('s_name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sportsmanagementsystem.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tournament_id', models.CharField(max_length=12)),
                ('team_1', models.CharField(max_length=10)),
                ('team_2', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('result', models.CharField(max_length=50)),
                ('s_name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sportsmanagementsystem.Sport')),
            ],
        ),
    ]
