# Generated by Django 2.0.5 on 2018-09-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmanagementsystem', '0012_auto_20180921_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='s_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsmanagementsystem.Sport'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sport_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsmanagementsystem.Sport'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='sport_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsmanagementsystem.Sport'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsmanagementsystem.Player'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='s_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsmanagementsystem.Sport'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='s_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsmanagementsystem.Sport'),
        ),
    ]
