# Generated by Django 2.0.5 on 2018-09-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmanagementsystem', '0021_auto_20180921_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsmanagementsystem.Student'),
        ),
    ]
