# Generated by Django 2.0.5 on 2018-09-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmanagementsystem', '0023_auto_20180921_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='sport_id',
            new_name='s_name',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='sport_id',
            new_name='s_name',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='sport_id',
            new_name='s_name',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='sport_id',
            new_name='s_name',
        ),
    ]
