# Generated by Django 2.1.1 on 2018-09-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmanagementsystem', '0024_auto_20180921_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
